# Calls to Worship {-}

Here's an example introduction.

God alone is the author of worship. Worship is not man's invention, but rather the natural function of his nature as an image bearing creature (Genesis 1:26). We are worshippers; God made us for this purpose. As the first question of the Westminster Shorter Catechism teaches:

Q. 1. What is the chief end of man? \
A. Man's chief end is to glorify God, and to enjoy Him forever.

The question is not, therefore, "Are we worshipping?" But, "Who are we worshipping?" 

Our desire for worship was not lessened, but was horribly corrupted by Adam's Fall. Subsequent to that event, it is in our depraved nature to "suppress the truth in unrighteousness," and rebelliously worship and serve created things rather than our Creator (Romans 1:18-25). Through the gift of regneration (spiritual rebirth in Christ), man's fellowship with God is restored, and we are able again to offer ourselves to God in true, Spiritual worship.  

Since God is both the author and only proper object of worship, and since restoration to our creative purpose as His worshippers is the only way to experience true peace and joy, God graciously and frequently commands us in His Word to lift our minds and hearts to Him in worship.

These calls to worship—found everywhere in Scripture, but most especially the Psalms—are typically recited at the beginning of worship to remind us of our duty to worship God alone, to wake us up from spiritual slumber, and to refocus our minds on His character and attributes. 

You will find here a growing collection of Scriptural calls to worship. These have been arranged by calls recited by the [pastor (or elder)](#from-the-fastor) alone, and calls recited [responsively between pastor and people](#responsive-calls). 


## From the Pastor {-}

Sing praise to the LORD, you His godly ones, and give thanks to His holy name. For His anger is but for a moment, His favor is for a lifetime; Weeping may last for the night, but a shout of joy comes in the morning. | Psalm 30:4-5

---

> I will bless the Lord at all times;\
His praise shall continually be in my mouth.\
My soul will make its boast in the Lord;\
The humble will hear it and rejoice.\
O magnify the Lord with me,\
And let us exalt His name together.
>
> --- Psalm 34:1-3

---

Your lovingkindness, O Lord, extends to the heavens,\
Your faithfulness reaches to the skies.\
Your righteousness is like the mountains of God;\
Your judgments are like a great deep.\
O Lord, You preserve man and beast.\
How precious is Your lovingkindness, O God!\
And the children of men take refuge in the shadow of Your wings.\
They drink their fill of the abundance of Your house;\
And You give them to drink of the river of Your delights.\
For with You is the fountain of life;\
In Your light we see light. | Psalm 36:5-9

---

Shout joyfully to the Lord, all the earth.\
Serve the Lord with gladness;\
Come before Him with joyful singing.\
Know that the Lord Himself is God;\
It is He who has made us, and not we ourselves;\
We are His people and the sheep of His pasture.\

Enter His gates with thanksgiving\
And His courts with praise.\
Give thanks to Him, bless His name.\
For the Lord is good;\
His lovingkindness is everlasting\
And His faithfulness to all generations. | Psalm 100

---

Oh give thanks to the LORD, call upon His name; Make known His deeds among the peoples. Sing to Him, sing praises to Him; Speak of all His wonders. Glory in His holy name; Let the heart of those who seek the LORD be glad. Seek the LORD and His strength; Seek His face continually. Remember His wonders which He has done, His marvels and the judgments uttered by His mouth, O seed of Abraham, His servant, O sons of Jacob, His chosen ones! He is the LORD our God; His judgments are in all the earth. | Psalm 105:1-7

---

Praise the Lord, all nations;
Laud Him, all peoples!
For His lovingkindness is great toward us,
And the truth of the Lord is everlasting.
Praise the Lord! | Psalm 117

---

I long for Your salvation, O LORD, And Your law is my delight. Let my soul live that it may praise You, And let Your ordinances help me. I have gone astray like a lost sheep; seek Your servant, For I do not forget Your commandments. | Psalm 119:174-176

---

Behold, God is my salvation, I will trust and not be afraid; for the LORD GOD is my strength and song, and He has become my salvation. | Isaiah 12:2

---

Ho! Every one who thirsts, come to the waters; And you who have no money come, buy and eat. Come, buy wine and milk Without money and without cost. Why do you spend money for what is not bread, And your wages for what does not satisfy? Listen carefully to Me, and eat what is good, And delight yourself in abundance. Incline your ear and come to Me. Listen, that you may live; And I will make an everlasting covenant with you. | Isaiah 55:1-3

---

Come and let us go up to the mountain of the LORD and to the house of the God of Jacob, That He may teach us about His ways and that we may walk in His paths. | Micah 4:2

---

Oh, the depth of the riches both of the wisdom and knowledge of God! How unsearchable are His judgments and unfathomable His ways! For WHO HAS KNOWN THE MIND OF THE LORD, OR WHO BECAME HIS COUNSELOR? Or WHO HAS FIRST GIVEN TO HIM THAT IT MIGHT BE PAID BACK TO HIM AGAIN? For from Him and through Him and to Him are all things. To Him be the glory forever. Amen. | Romans 11:33-36

---

"Awake, sleeper, 
And arise from the dead, 
And Christ will shine on you." | Ephesians 5:14

---

Draw near to God and He will draw near to you. Cleanse your hands, you sinners; and purify your hearts, you double-minded. Be miserable and mourn and weep; let your laughter be turned into mourning and your joy to gloom. Humble yourselves in the presence of the Lord, and He will exalt you. | James 4:8-10

---

God is opposed to the proud, but gives grace to the humble. Therefore humble yourselves under the mighty hand of God, that He may exalt you at the proper time. | 1 Peter 5:5-6

## Responsive Calls {-}

**_Pastor:_** Blessed are You, O Lord God of Israel our father, forever and ever.

**_Congregation_**: Yours, O Lord, is the greatness and the power and the glory and the victory and the majesty, indeed everything that is in the heavens and the earth; Yours is the dominion, O Lord, and You exalt Yourself as head over all.

**_Pastor_**: Both riches and honor come from You, and You rule over all, and in Your hand is power and might; and it lies in Your hand to make great and to strengthen everyone.

**_Congregation_**: Now therefore, our God, we thank You, and praise Your glorious name.

  | 1 Chronicles 29:10b-13 |

---

Pastor: O Lord, how my adversaries have increased! Many are rising up against me. Many are saying of my soul, “There is no deliverance for him in God.” 

Congregation: But You, O Lord, are a shield about me, My glory, and the One who lifts my head.
 
Pastor: I was crying to the Lord with my voice, And He answered me from His holy mountain. I lay down and slept; I awoke, for the Lord sustains me. I will not be afraid of ten thousands of people Who have set themselves against me round about.
 
All: Arise, O Lord; save me, O my God! For You have smitten all my enemies on the cheek; You have shattered the teeth of the wicked. Salvation belongs to the Lord; Your blessing be upon Your people! 
 
  | Psalm 3 |

---

Pastor: The law of the LORD is perfect,

Congregation: restoring the soul.

Pastor: The testimony of the LORD is sure,

Congregation: making wise the simple.

Pastor: The precepts of the LORD are right,

Congregation: rejoicing the heart.

Pastor: The commandment of the LORD is pure,

Congregation: enlightening the eyes.

Pastor: The fear of the LORD is clean,

Congregation: enduring forever.

Pastor: The judgments of the LORD are true;

Congregation: they are righteous altogether.

All: They are more desirable than gold, yes, than much fine gold; sweeter also than honey and the drippings of the honeycomb. Moreover, by them Your servant is warned; in keeping them there is great reward.

| Psalm 19:7-11 |

---

Pastor: Let us remember the deeds of the LORD; and His wonders of old.

Congregation:  Many, O LORD, are the wonders which You have done, And Your thoughts toward us; There is none to compare with You. If we would declare and speak of them, they would be too numerous to count.

Pastor: Your way, O God, is holy; What god is great like our God?

Congregation: You are the God who works wonders; You have made known Your strength among the peoples.

| Psalm 40:5; 77:11, 13-14 |

---

Pastor: Bless our God, O peoples, And sound His praise abroad, Who keeps us in life and does not allow our feet to slip.

Congregation: Bless the LORD, O my soul, and all that is within me, bless His holy name.

| Psalm 66:8-9; 103:1 |

---

Pastor: Come, let us worship and bow down, Let us kneel before the LORD our Maker.

Congregation: For He is our God, And we are the people of His pasture and the sheep of His hand.

Pastor: Today, if you would hear His voice, Do not harden your hearts.

| Psalm 96:6-8 |

---

Pastor: Sing to the LORD a new song; Sing to the LORD, all the earth. Sing to the LORD, bless His name; Proclaim good tidings of His salvation from day to day.

Congregation: Tell of His glory among the nations, His wonderful deeds among all the peoples.

All: For great is the LORD and greatly to be praised; He is to be feared above all gods.

| Psalm 96:1-4 |

---

Pastor: The LORD reigns, let the earth rejoice; Let the many islands be glad.

People: Clouds and thick darkness surround Him; Righteousness and justice are the foundation of His throne. 

Pastor: Fire goes before Him and burns up His adversaries round about. His lightnings lit up the world; the earth saw and trembled.

People: The mountains melted like wax at the presence of the LORD, At the presence of the Lord of the whole earth.

Pastor: The heavens declare His righteousness, And all the peoples have seen His glory.

People: Let all those be ashamed who serve graven images, Who boast themselves of idols; Worship Him, all you gods.

Pastor: Zion heard this and was glad, and the daughters of Judah have rejoiced Because of Your judgments, O LORD.

People: For You are the LORD Most High over all the earth; You are exalted far above all gods.

Pastor: Hate evil, you who love the LORD, Who preserves the souls of His godly ones; He delivers them from the hand of the wicked.

People: Light is sown like seed for the righteous And gladness for the upright in heart.

Pastor: Be glad in the LORD, you righteous ones, And give thanks to His holy name.

| Psalm 97 |

---

Pastor: Shout joyfully to the LORD, all the earth. Serve the LORD with gladness; Come before Him with joyful singing.

People: Know that the LORD Himself is God; It is He who has made us, and not we ourselves; We are His people and the sheep of His pasture.

Pastor: Enter His gates with thanksgiving And His courts with praise. Give thanks to Him, bless His name.

People: For the LORD is good; His lovingkindness is everlasting And His faithfulness to all generations.

| Psalm 100 |

---

Pastor: Praise the LORD! I will give thanks to the LORD with all my heart, In the company of the upright and in the assembly.

Congregation: Great are the works of the LORD; They are studied by all who delight in them.

Pastor: Splendid and majestic is His work, And His righteousness endures forever.

Congregation: He has made His wonders to be remembered; The LORD is gracious and compassionate. He has given food to those who fear Him; He will remember His covenant forever.

Pastor: He has made known to His people the power of His works, In giving them the heritage of the nations.

Congregation: The works of His hands are truth and justice; All His precepts are sure. They are upheld forever and ever; They are performed in truth and uprightness.

Pastor: He has sent redemption to His people; He has ordained His covenant forever; Holy and awesome is His name.

All: The fear of the LORD is the beginning of wisdom; A good understanding have all those who do His commandments; His praise endures forever.

| Psalm 111:1-10 |

---

Pastor: Praise the LORD! Praise, O servants of the LORD, Praise the name of the LORD. Blessed be the name of the LORD From this time forth and forever.

Congregation: From the rising of the sun to the going down of the same, the name of the LORD is to be praised.

| Psalm 113:1-3 |

---

Pastor: Great is the LORD, and greatly to be praised, In the city of our God, His holy mountain.

Congregation: Come and let us go up to the mountain of the LORD and to the house of the God of Jacob, That He may teach us about His ways and that we may walk in His paths. 

| Psalm 48:1; Micah 4:2 |

---

Pastor: As Jesus was approaching Jericho, a certain blind man was sitting by the road, begging. Now hearing a multitude going by, he began to inquire what this might be. And they told him that Jesus of Nazareth was passing by. And he called out, saying…

Congregation: "Jesus, Son of David, have mercy on me!"

Pastor: And those who led the way were sternly telling him to be quiet; but he kept crying out all the more…

Congregation: "Son of David, have mercy on me!"

Pastor: And Jesus stopped and commanded that he be brought to Him; and when he had come near, He questioned him, “What do you want Me to do for you?” And he said…

Congregation: "Lord, I want to regain my sight!"

Pastor: And Jesus said to him, "Receive your sight; your faith has made you well." And immediately he regained his sight, and began following Him, glorifying God; and when all the people saw it, they gave praise to God.

| Luke 18:35-43 |
