# Prayers

This section is still a work in progress, but please check out the prayer categories to the left for help in your worship planning.

## Invocations

Merciful Father,

We come into Your presence now to praise Your holy name; To humble ourselves before Your heavenly throne and bring our sacrifices of praise before You. We ask that you would break us of our prideful, lofty thoughts and that You would rid us of all self-righteousness as we meet with You—the Holy God—at this hour. Cause us to give ourselves to Your attention and not to our own.

Would you please work in our hearts by Your Holy Spirit and would you do a mighty work this morning as we sing, read, and hear Your Word? Would you convict us of our sin and cause us to have true faith and repentance so that when we go out from this place we would be renewed in Your grace?

Father, we ask that the words we say and the thoughts of our hearts would be acceptable in Your sight—You who are our Rock and our Redeemer. In the name of Your dear son Jesus we pray. Amen.

Philip J. Moyer

---

Heavenly Father,

We are gathered here in Your presence to worship Your holy name.

You know our frame. You know our hearts. You know that we are but dust and that we have nothing to offer you, but to humble ourselves before Your awesome throne.

Father, by Your Holy Spirit, through the blood of Your Son Jesus Christ, would you put a right spirit within us this morning as bring our sacrifices of praise to You? You have said in Your word that whoever calls upon the name of the Lord will be saved. And we call upon Your name this morning—believing—having confidence that you will be faithful to Your word. Have mercy on us, we pray. And may you receive all honor and glory now and forever. 

Amen. 

Philip J. Moyer

---

{For use during services when the Lord's Supper will be served}

Heavenly Father, Maker of heaven and earth,

You are our only help and we can do nothing apart from your grace. Would you please condescend to us this morning? Please be kind to meet with us and show Yourself all-glorious. Please be with the singing, the reading, the preaching of Your word, and be with us as we give offerings to you. Strengthen us by Your meal as we celebrate the Lord’s Supper together and increase our faith in You this morning.

Lord, give us your Spirit so that we may worship you aright. Look on us with favor as we give You the glory that is due Your name. Please take our filthy rags, our humble sacrifices of praise, and make them pure and beautiful in Your sight. May You receive all the glory this morning as we worship You.

In the name of Your dear Son, Jesus we pray. Amen.

Philip J. Moyer

## For Illumination

Empty

## Litanies

Empty

## After Creed

Heavenly Father, We have just confessed our faith in You and the path that You have made for us unto salvation through Jesus Christ. Father, we pray that You would make us not only confessors by mouth, but make our hearts and our actions to agree with these truths we have just confessed corporately.

Now, we pray, heavenly Father, that You would strengthen us through the reading and preaching of Your word. Open our ears to hear Your word and give us soft, humble hearts that are ready to receive Your instruction. And may Your Holy Spirit fall upon our pastor with great power as he preaches to us this morning. To you be all honor and glory and power forever. Amen.

Philip J. Moyer

## Communion

Father God, we give you praise that your Son, Jesus Christ, was obedient to death, even death on the cross; and we confess that, therefore, He is highly exalted and is given a name that is above every name; that at the name of Jesus, every knee should bow and every tongue confess, 'He is Lord,' to the glory of God the Father.

Father, meet us at this table. Would you please send your Spirit to strengthen the weak, to give faith to the doubting, to give forgiveness to the bitter, to give purity to the lustful, to give charity to the greedy? Father, give us whatever we need, that through this Body and Blood--broken and shed for us--we might go forth from this place cleansed through your grace. 

O Lamb of God, that takes away the sins of the world, have mercy on us. 

In Jesus' name, Amen.

---Rev. Timothy B. Bayly
