# Confessions of Sin

Transported by a vision into the throne room of God, the prophet Isaiah was compelled by the heavenly sight to cry out, "Woe is me, for I am ruined! Because I am a man of unclean lips, and I live among a people of unclean lips; For my eyes have seen the King, the LORD of hosts” (Isaiah 6:5).

Confession of sin should likewise be our first and most natural response when coming before our holy God in worship. The Scriptures teach that "If we say that we have no sin, we are deceiving ourselves and the truth is not in us." Moreover, we are assured that "If we confess our sins, [God] is faithful and righteous to forgive us our sins and to cleanse us from all unrighteousness" (1John 1:8-9). To confess our sins corporately to God, therefore, is to demonstrate faith in His willingness to forgive, and—when followed by an assurance of God's pardon—to experience His glorious Gospel at work in our midst. 

Here are some prayers of confession from Scripture and history to help guide you in the work of confession.

## Scriptural 

O my God, I am ashamed and embarrassed to lift up my face to You, my God, for our iniquities have risen above our heads and our guilt has grown even to the heavens. Since the days of our fathers to this day we have been in great guilt, and on account of our iniquities we, our kings and our priests have been given into the hand of the kings of the lands, to the sword, to captivity and to plunder and to open shame, as it is this day. But now for a brief moment grace has been shown from the LORD our God, to leave us an escaped remnant and to give us a peg in His holy place, that our God may enlighten our eyes and grant us a little reviving in our bondage. For we are slaves; yet in our bondage our God has not forsaken us, but has extended lovingkindness to us in the sight of the kings of Persia, to give us reviving to raise up the house of our God, to restore its ruins and to give us a wall in Judah and Jerusalem. Now, our God, what shall we say after this? For we have forsaken Your commandments, which You have commanded by Your servants the prophets, saying, 'The land which you are entering to possess is an unclean land with the uncleanness of the peoples of the lands, with their abominations which have filled it from end to end and with their impurity. So now do not give your daughters to their sons nor take their daughters to your sons, and never seek their peace or their prosperity, that you may be strong and eat the good things of the land and leave it as an inheritance to your sons forever.' After all that has come upon us for our evil deeds and our great guilt, since You our God have requited us less than our iniquities deserve, and have given us an escaped remnant as this, shall we again break Your commandments and intermarry with the peoples who commit these abominations? Would You not be angry with us to the point of destruction, until there is no remnant nor any who escape? O LORD God of Israel, You are righteous, for we have been left an escaped remnant, as it is this day; behold, we are before You in our guilt, for no one can stand before You because of this. | Ezra 9:6-15

---

Alas, O Lord, the great and awesome God, who keeps His covenant and lovingkindness for those who love Him and keep His commandments, we have sinned, committed iniquity, acted wickedly and rebelled, even turning aside from Your commandments and ordinances. Moreover, we have not listened to Your servants the prophets, who spoke in Your name to our kings, our princes, our fathers and all the people of the land. Righteousness belongs to You, O Lord, but to us open shame, as it is this day--to the men of Judah, the inhabitants of Jerusalem and all Israel, those who are nearby and those who are far away in all the countries to which You have driven them, because of their unfaithful deeds which they have committed against You. Open shame belongs to us, O Lord, to our kings, our princes and our fathers, because we have sinned against You. To the Lord our God belong compassion and forgiveness, for we have rebelled against Him; nor have we obeyed the voice of the LORD our God, to walk in His teachings which He set before us through His servants the prophets. Indeed all Israel has transgressed Your law and turned aside, not obeying Your voice; so the curse has been poured out on us, along with the oath which is written in the law of Moses the servant of God, for we have sinned against Him. Thus He has confirmed His words which He had spoken against us and against our rulers who ruled us, to bring on us great calamity; for under the whole heaven there has not been done anything like what was done to Jerusalem. As it is written in the law of Moses, all this calamity has come on us; yet we have not sought the favor of the LORD our God by turning from our iniquity and giving attention to Your truth. Therefore the LORD has kept the calamity in store and brought it on us; for the LORD our God is righteous with respect to all His deeds which He has done, but we have not obeyed His voice. And now, O Lord our God, who have brought Your people out of the land of Egypt with a mighty hand and have made a name for Yourself, as it is this day--we have sinned, we have been wicked. O Lord, in accordance with all Your righteous acts, let now Your anger and Your wrath turn away from Your city Jerusalem, Your holy mountain; for because of our sins and the iniquities of our fathers, Jerusalem and Your people have become a reproach to all those around us. So now, our God, listen to the prayer of Your servant and to his supplications, and for Your sake, O Lord, let Your face shine on Your desolate sanctuary. O my God, incline Your ear and hear! Open Your eyes and see our desolations and the city which is called by Your name; for we are not presenting our supplications before You on account of any merits of our own, but on account of Your great compassion. O Lord, hear! O Lord, forgive! O Lord, listen and take action! For Your own sake, O my God, do not delay, because Your city and Your people are called by Your name. | Daniel 9:4-19

## Traditional

ALMIGHTY and most merciful Father; we have erred, and strayed from thy ways like lost sheep. We have followed too much the devices and desires of our own hearts. We have offended against thy holy laws. We have left undone those things which we ought to have done; and we have done those things which we ought not to have done; and there is no health in us. But thou, O Lord, have mercy upon us, miserable offenders. Spare thou them, O God, who confess their faults. Restore thou those who are penitent; According to thy promises declared unto mankind in Christ Jesus our Lord. And grant, O most merciful Father, for his sake; That we may hereafter live a godly, righteous, and sober life, To the glory of thy holy Name. Amen.

1549 Book of Common Prayer

Lord God, eternal and almighty Father: We acknowledge before your holy majesty that we are poor sinners, conceived and born in guilt and in corruption, prone to do evil, unable of our own power to do good. Because of our sin, we endlessly violate your holy commandments. But, O Lord, with heartfelt sorrow we repent and turn away from all our offenses. We condemn ourselves and our evil ways, with true sorrow asking that your grace will relieve our distress. Have compassion on us, most gracious God, Father of mercies, for the sake of your son Jesus Christ our Lord. And in removing our guilt, also grant us daily increase of the grace of your Holy Spirit, and produce in us the fruits of holiness and of righteousness pleasing in your sight: Through Jesus Christ our Lord. Amen.

Adapted from John Calvin's Geneva Liturgy of 1543

Almighty God, we are unworthy to come into your presence, because of our many sins. We do not deserve any grace or mercy from you, if you dealt with us as we deserve. We have sinned against you, O Lord, and we have offended you. And yet, O Lord, as we acknowledge our sins and offenses, so also do we acknowledge you to be a merciful God, a loving and favorable Father, to all who turn to you. And so we humbly ask you, for the sake of Christ your son, to show mercy to us, and forgive us all our offenses. Forgive the sins of our youth, and the sins of our old age. By your Spirit, O God, take possession of our hearts, so that, not only the actions of our life, but also the words of our mouths, and the smallest thought of our minds, may be guided and governed by you. Through Jesus Christ our Lord, to whom, with you and the Holy Spirit, be all honor and glory, now and forever. Amen.

Adapted from John Knox's Liturgy of 1560

## Modern

Heavenly Father,

It is our privilege to confess our sins before You because You have promised in Your Word that if we confess our sins, You are faithful to cleanse us from all unrighteousness through the blood of Jesus Christ, and that we will receive the promise of eternal life. 

Father, we have sinned, and we ask that you would please forgive us for how we have broken Your perfect and Holy Law. Forgive us for running away from You and turning our backs on You.

Like sheep we have gone astray and have turned to our own ways. We have turned to our own earthly desires—to our own flesh, and in doing so we have turned to strange flesh. We have turned to other gods and we have sinned against You. We have done unlawful things in Your sight. Father, please forgive us and renew us in Your grace.

We pray in Jesus name, Amen.

Philip J. Moyer

---

Heavenly Father, Merciful Father,
 
We come before you now as a people who are heavy with sin. Our sins weigh us down and we are unable to help ourselves. We confess that we have not turned to You in our distress. We have not called upon Your name in times of trouble, but rather in our wickedness we have sought to drive you away because of our shame. We have deceived ourselves seeking to be rescued by pleasures and entertainments rather than coming before You, the holy God, to cry to You for help and to have our prayers answered.
 
We have sinned thinking that we can fix ourselves. We are guilty of clinging to the very sins for which Your Son, Jesus Christ, died on the cross. Forgive us for our pride and for not bringing our burdens to You, thinking that they are not too heavy for us to bear. 
 
Father we cannot bear the awful load of our sin. So please, heavenly Father, by the blood of Your Son Jesus Christ, remove from us this burden and save us. Restore to us the joy of Your salvation and renew a right spirit within us. 
 
Father, You are our only Helper; our only Redeemer; the only One who can save.
 
Lord, hear our prayers and deliver us this day so that we would no longer be slaves to sin, but that we would be set free to dwell in Your peaceful Kingdom. 
 
We ask in the powerful Name of our Savior Jesus Christ. Amen.
 
Philip J. Moyer

---
Prayer of Confession for Pentecost

{After singing Come, Thou Almighty King}

Gracious Heavenly Father,

We know that You have promised Your Holy Spirit to all who trust in You. We have just asked the Holy Spirit to rule in each of our hearts and to never depart from us.  Yet, we confess that we have sinned in many ways against You and Your Spirit, and have behaved as if He does not live in our hearts.

When you have healed us from sickness, we have attributed our healing to earthly things and we have not acknowledged You for the miracles You have done.

When you have given us gifts, we have refused to be content or thankful for your mercies to us and have instead envied your gifts to others.

We are an ungrateful people.

When you have touched our lips with your Holy Spirit, we have shut our mouths so that we would not have to bear the reproach of the words that we would say.

When you have spoken to us, we have shut our ears, afraid of what You might call us to do. You have given us Your Word, yet we have refused to walk in it.  We have persisted in willful sin and have not repented.

We are a disobedient people.

In these ways, and many others, we have sinned against Your Holy Spirit and we ask that You would please forgive us, O heavenly Father, for how we have quenched Your Holy Spirit.

We pray that you would restore to us the joy of Your salvation and renew a right spirit within us. We repent of our sin. And we, as Your covenant people, trust in the promises You have made to us—having faith in Christ’s provision and believing the power of the Holy Spirit to heal us and give us the ability to obey.

Renew our hearts, we pray.

In the name of the Father, Son, and Holy Spirit, Amen.

Philip J. Moyer

