--- 
title: "A Liturgy Resource from Warhorn Media"
author: "Warhorn Media"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This site is a resource for planning worship services, providing lists of various elements as a quick reference."
---

# Liturgy {-}

This site is a resource for planning worship services, providing lists of various elements as a quick reference.

The word "liturgy" can sound intimidating, but it is merely a composite Greek word meaning public work or duty. In Christian use, liturgy refers to the public service of God’s people. Thus, it consists of whatever actions we perform together to express our devotion to the Lord.

Under the Old Covenant, God had prescribed a gracious but elaborate service of animal sacrifices and votive offerings to be practiced in a restricted location (the tabernacle initially, later the temple in Jerusalem), through the mediation of the Levitical priesthood. Though these ancient ceremonies were fulfilled and done away with in the death of Christ, yet God has prescribed for the New Testament Church a liturgy of her own, albeit a far simpler and less restrictive one. This New Covenant liturgy is delineated in Acts 2:42, where we read that the first Christians were “continually devoting themselves to the Apostles’ teaching and to fellowship, to the breaking of bread and to prayer.” These are the basic categories of public worship subsequent to the coming of Christ and the pouring out of His Spirit at Pentecost.

While there are perhaps various ways of faithfully giving expression to these simple Apostolic devotions, the Protestant Church has historically seen fit to make use of the elements found in the menu bar. (Note: song is a subcategory of prayer, dealt with here.) Under each category you will find examples from Scripture and history to assist you in preparing to lead God's people in their spiritual service of worship. 
